#!/usr/bin/env python3
"""Async Comprehensions

This script contains a coroutine that collects random numbers using an async
comprehension over an asynchronous generator.
"""

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Coroutine that collects 10 random numbers using an async comprehension
    over async_generator.

    This function uses an asynchronous comprehension to collect 10 random
    numbers generated by the async_generator coroutine.

    Returns:
        List[float]: A list of 10 random numbers.
    """
    return [num async for num in async_generator()]
